<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCi7Fbup\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCi7Fbup/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCi7Fbup.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCi7Fbup\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCi7Fbup\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ci7Fbup',
    'container.build_id' => 'eef8d544',
    'container.build_time' => 1540814179,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCi7Fbup');
